floppy: floppy.c help.c fmount.c showfat.c structure.c showsector.c transverse.c
	gcc -o Floppy floppy.c help.c fmount.c showfat.c structure.c showsector.c transverse.c readline.c folderdepth1.c removespaces.c
