floppy: help.c fmount.c showfat.c structure.c showsector.c transverse.c path.c flopshell.c readline.c removespaces.c folderdepth1.c mynode.c
	gcc -o Flopshell help.c fmount.c showfat.c structure.c showsector.c transverse.c path.c flopshell.c readline.c removespaces.c folderdepth1.c mynode.c
